name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Run Type Check, Linters & Tests
    runs-on: ubuntu-latest

    env:
      SKIP_ENV_VALIDATION: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn

      - name: Check types
        run: yarn type-check

      - name: Check linting
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v5
